### ISSUE TITLE
WithTaxonomies cannot retrieve all terms

### ISSUE THREAD

**Issue by sndrgb** [caffeinalab/malini#2]
Ieri cercando di usare il `decorator` delle `taxonomies` ho visto che le custom taxonomies non me le tirava giù, io ho risolto modificando riga 29 di WithTaxonomies con:

`return wp_get_post_terms($wp_post->ID, get_post_taxonomies($wp_post));`

forse c'è un modo migliore però per ora ho risolto cosi, se serve faccio pr

**Comment by Polmonite** [comment]
Assolutamente corretto quanto hai fatto e grazie per averlo fatto notare.
Apri pure pr e vediamo di aggiungerla.

Grazie!
